Do not die on JSON error in get_key_from_all_sessions
LemonLDAPNG/Apache-Session-Browseable pull request #39
Opened 2023-10-06 13:28 UTC by jeremie-pierson

When an error occurs on unserializing a JSON session, the unserialize() sub in lib/Apache/Session/Serialize/JSON.pm calls die().

In other session stores (for example LDAP), when unserialize() is called in the context of get_key_from_all_sessions(), it uses eval{} to catch the error. But here in the Redis store, it does not and get_key_from_all_sessions() is interrupted.

It causes the purgeCentralCache script in lemonldap-ng to exit early and not purge any sessions, when it encounters an invalid/corrupted session.

Please keep in mind that, although this fix is very short, my knowledge of Perl is extremely thin :-)

2023-10-06 13:48 UTC, jeremie-pierson commented
Hopefully fixes #40 .

2023-10-09 09:59 UTC, maxbes requested changes

2023-10-09 09:59 UTC, maxbes commented on lib/Apache/Session/Browseable/Redis.pm
> +            my $tmp = eval { unserialize($v) };
This call is already inside an eval. I don't see how it helps and I can't reproduce the failure mentionned in #40

2023-10-10 08:04 UTC, jeremie-pierson commented
This bug was corrected 4 years ago. My local version was ancient and I didn't check this before filing a bug. Oops.

2023-10-10 08:04 UTC, closed without merging